services:
  nginx:
    image: nginx:1.29.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - public
    restart: unless-stopped

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - "3000:3000"  # Exposed for standalone development
    networks:
      - public
    environment:
      NODE_ENV: development
      # Uncomment polling if file changes aren't detected on your host
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    develop:
      watch:
        - path: ./frontend
          target: /code
          action: sync
          ignore:
            - node_modules/
            - .next/
            - .git/
            - Dockerfile*
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild

  backend:
    build:
      context: backend
      target: development
    ports:
      - "8080:8080"  # Exposed for standalone development
    environment:
      - DATABASE_DB=homigo
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - PORT=8080
      - NODE_ENV=development
      - CORS_ORIGIN=https://localhost
      - ENCRYPTION_KEY=/run/secrets/enc-key
      - JWT_SECRET=/run/secrets/jwt-secret
      - JWT_EXPIRES_IN=1h
    secrets:
      - db-password
      - enc-key
      - jwt-secret
    volumes:
      - ./backend/uploads:/code/uploads
    networks:
      - public
      - private
    depends_on:
      - db
    develop:
      watch:
        - path: ./backend
          target: /code
          action: sync
          ignore:
            - node_modules/
            - .git/
            - dist/
            - Dockerfile*
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild

  db:
    image: mysql:8.0.44
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - private
    environment:
      - MYSQL_DATABASE=homigo
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    restart: unless-stopped
    ports:
      - "8081:80"          
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD_FILE: /run/secrets/db-password
      UPLOAD_LIMIT: 512M
    secrets:
      - db-password
    networks:
      - private
    depends_on:
      - db

networks:
  public:
  private:

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
  enc-key:
    file: db/enc_key.txt
  jwt-secret:
    file: backend/secrets/jwt.txt